#!/usr/bin/env python

import rospy
from sensehat_driver import sensehat_environment_publisher

if __name__ == '__main__':
    
    rospy.init_node("sensehat_environment_publisher_node", anonymous=True)
    
    sensehat_environment_pub = sensehat_environment_publisher.SenseHatEnvironmentPublisher()
    
    try:
        rate = rospy.Rate(30)    

        while not rospy.is_shutdown():
            sensehat_environment_pub.publish_environment_data()
            rate.sleep()         
    except rospy.ROSInterruptException:
        pass
