#!/usr/bin/env python

import rospy
from sensehat_driver.msg import IMUOrientationEuler
from sense_hat import SenseHat
from sensor_msgs.msg import Imu

def display_compass(data):
    if (45 <= data.yaw < 135):
        sense.show_letter("E")
    elif (135 <= data.yaw < 225):
        sense.show_letter("S")
    elif (225 <= data.yaw < 315):
        sense.show_letter("W")
    else:
        sense.show_letter("N")

def subscribe_imu_data():
    rospy.Subscriber("imu_orientation_euler", IMUOrientationEuler, display_compass)
    rospy.spin()

if __name__ == '__main__':
    rospy.init_node("sensehat_compass_display") 
    sense = SenseHat()
    sense.clear()
    subscribe_imu_data()

    

