#!/usr/bin/env python

import rospy
from sensehat_driver.srv import *
from sense_hat import SenseHat

def handle_calc_temp_diff(request):
    sense_temp = sense.get_temperature() 
    
    return TemperatureDifferenceResponse(sense_temp - request.input_temp)

def calc_temp_diff_server():
    rospy.init_node("sensehat_temp_diff_server")
    service = rospy.Service("calc_temp_diff", TemperatureDifference, handle_calc_temp_diff)
    rospy.loginfo("Starting ROS service: sensehat_driver calc_temp_diff")
    rospy.spin()

if __name__ == "__main__":
    sense = SenseHat()
    calc_temp_diff_server()
